# Generated by Django 3.0.4 on 2020-03-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('D', 'Doctor'), ('P', 'Patient')], default='D', max_length=10),
        ),
    ]
