# Generated by Django 3.0.4 on 2020-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('d', 'doctor'), ('p', 'patient')], default='doctor', max_length=10),
        ),
    ]
