# Generated by Django 3.0.4 on 2020-04-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=20)),
                ('img', models.FileField(default='default.png', upload_to='myapp/img/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.FileField(default='default.png', upload_to='myapp/img/'),
        ),
    ]
