# Generated by Django 3.0.4 on 2020-05-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200418_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default='123'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(default='Request Sent', max_length=20)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
