# Generated by Django 3.0.4 on 2020-05-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=20)),
                ('lname', models.CharField(blank=True, max_length=20)),
                ('phoneno', models.CharField(blank=True, max_length=20)),
                ('service', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=5)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('datetime', models.CharField(blank=True, max_length=20)),
                ('wardno', models.CharField(blank=True, max_length=10)),
                ('doctorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Doctor')),
            ],
        ),
    ]
