# Generated by Django 3.0.4 on 2020-05-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctorname',
            new_name='doc_id',
        ),
    ]
