# Generated by Django 3.0.4 on 2020-05-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200516_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
