# Generated by Django 3.0.4 on 2020-05-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientprofilepic',
            field=models.FileField(default='default.png', upload_to='myapp/img/'),
        ),
    ]
