# Generated by Django 3.0.4 on 2020-05-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200518_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
