# Generated by Django 3.0.4 on 2020-05-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentno', models.CharField(blank=True, max_length=10)),
                ('patientname', models.CharField(blank=True, max_length=20)),
                ('doctorname', models.CharField(blank=True, max_length=20)),
                ('paymentdate', models.CharField(blank=True, max_length=20)),
                ('totalamount', models.CharField(blank=True, max_length=10)),
                ('paymentstatus', models.CharField(blank=True, max_length=30)),
                ('paymentmethod', models.CharField(blank=True, max_length=30)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Patient')),
            ],
        ),
    ]
